id: PB9798E62
initial_creation_type: ocr
source_metadata:
  volumes:
    086da8da1c3b47a4ac0bbde43bb8aa67:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཚིགས་སུ་བཅད་པ་ཕྱེད་དང་ལྔ།
      total_pages: 1902
      volume_number: 26
